# Generated by Django 3.2.8 on 2021-10-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_fooditem_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='user_rating',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='user rating'),
        ),
    ]
